package com.moov.pim.analytics.domain;

public enum AuditAction {
    CREATE, UPDATE, DELETE, VALIDATE, REJECT, PUBLISH, ROLLBACK, LOGIN, LOGIN_FAILED, EXPORT, DATA_ANONYMIZED, DATA_EXPORT_REQUESTED
}
