export interface Country {
  code: string;
  name: string;
  dial: string;
  digits: number;
}

export const COUNTRIES: Country[] = [
  // Afrique de l'Ouest (prioritaires Moov Africa)
  { code: "bf", name: "Burkina Faso", dial: "+226", digits: 8 },
  { code: "ci", name: "Côte d'Ivoire", dial: "+225", digits: 10 },
  { code: "ml", name: "Mali", dial: "+223", digits: 8 },
  { code: "ne", name: "Niger", dial: "+227", digits: 8 },
  { code: "tg", name: "Togo", dial: "+228", digits: 8 },
  { code: "bj", name: "Bénin", dial: "+229", digits: 8 },
  { code: "sn", name: "Sénégal", dial: "+221", digits: 9 },
  { code: "gn", name: "Guinée", dial: "+224", digits: 9 },
  { code: "gh", name: "Ghana", dial: "+233", digits: 9 },
  { code: "ng", name: "Nigéria", dial: "+234", digits: 10 },
  { code: "gm", name: "Gambie", dial: "+220", digits: 7 },
  { code: "gw", name: "Guinée-Bissau", dial: "+245", digits: 7 },
  { code: "lr", name: "Libéria", dial: "+231", digits: 7 },
  { code: "sl", name: "Sierra Leone", dial: "+232", digits: 8 },
  { code: "cv", name: "Cap-Vert", dial: "+238", digits: 7 },
  { code: "mr", name: "Mauritanie", dial: "+222", digits: 8 },

  // Afrique Centrale
  { code: "cm", name: "Cameroun", dial: "+237", digits: 9 },
  { code: "ga", name: "Gabon", dial: "+241", digits: 7 },
  { code: "td", name: "Tchad", dial: "+235", digits: 8 },
  { code: "cf", name: "Centrafrique", dial: "+236", digits: 8 },
  { code: "cg", name: "Congo", dial: "+242", digits: 9 },
  { code: "cd", name: "RD Congo", dial: "+243", digits: 9 },
  { code: "gq", name: "Guinée équatoriale", dial: "+240", digits: 9 },
  { code: "st", name: "São Tomé-et-Príncipe", dial: "+239", digits: 7 },

  // Afrique de l'Est
  { code: "ke", name: "Kenya", dial: "+254", digits: 9 },
  { code: "tz", name: "Tanzanie", dial: "+255", digits: 9 },
  { code: "ug", name: "Ouganda", dial: "+256", digits: 9 },
  { code: "rw", name: "Rwanda", dial: "+250", digits: 9 },
  { code: "bi", name: "Burundi", dial: "+257", digits: 8 },
  { code: "et", name: "Éthiopie", dial: "+251", digits: 9 },
  { code: "er", name: "Érythrée", dial: "+291", digits: 7 },
  { code: "dj", name: "Djibouti", dial: "+253", digits: 8 },
  { code: "so", name: "Somalie", dial: "+252", digits: 8 },
  { code: "ss", name: "Soudan du Sud", dial: "+211", digits: 9 },

  // Afrique Australe
  { code: "za", name: "Afrique du Sud", dial: "+27", digits: 9 },
  { code: "mg", name: "Madagascar", dial: "+261", digits: 9 },
  { code: "mz", name: "Mozambique", dial: "+258", digits: 9 },
  { code: "zw", name: "Zimbabwe", dial: "+263", digits: 9 },
  { code: "zm", name: "Zambie", dial: "+260", digits: 9 },
  { code: "mw", name: "Malawi", dial: "+265", digits: 9 },
  { code: "bw", name: "Botswana", dial: "+267", digits: 8 },
  { code: "na", name: "Namibie", dial: "+264", digits: 9 },
  { code: "ao", name: "Angola", dial: "+244", digits: 9 },
  { code: "ls", name: "Lesotho", dial: "+266", digits: 8 },
  { code: "sz", name: "Eswatini", dial: "+268", digits: 8 },
  { code: "mu", name: "Maurice", dial: "+230", digits: 8 },
  { code: "km", name: "Comores", dial: "+269", digits: 7 },
  { code: "sc", name: "Seychelles", dial: "+248", digits: 7 },

  // Afrique du Nord
  { code: "ma", name: "Maroc", dial: "+212", digits: 9 },
  { code: "dz", name: "Algérie", dial: "+213", digits: 9 },
  { code: "tn", name: "Tunisie", dial: "+216", digits: 8 },
  { code: "ly", name: "Libye", dial: "+218", digits: 9 },
  { code: "eg", name: "Égypte", dial: "+20", digits: 10 },
  { code: "sd", name: "Soudan", dial: "+249", digits: 9 },

  // Europe
  { code: "fr", name: "France", dial: "+33", digits: 9 },
  { code: "be", name: "Belgique", dial: "+32", digits: 9 },
  { code: "ch", name: "Suisse", dial: "+41", digits: 9 },
  { code: "de", name: "Allemagne", dial: "+49", digits: 10 },
  { code: "gb", name: "Royaume-Uni", dial: "+44", digits: 10 },
  { code: "es", name: "Espagne", dial: "+34", digits: 9 },
  { code: "it", name: "Italie", dial: "+39", digits: 10 },
  { code: "pt", name: "Portugal", dial: "+351", digits: 9 },
  { code: "nl", name: "Pays-Bas", dial: "+31", digits: 9 },
  { code: "at", name: "Autriche", dial: "+43", digits: 10 },
  { code: "pl", name: "Pologne", dial: "+48", digits: 9 },
  { code: "se", name: "Suède", dial: "+46", digits: 9 },
  { code: "no", name: "Norvège", dial: "+47", digits: 8 },
  { code: "dk", name: "Danemark", dial: "+45", digits: 8 },
  { code: "fi", name: "Finlande", dial: "+358", digits: 9 },
  { code: "ie", name: "Irlande", dial: "+353", digits: 9 },
  { code: "gr", name: "Grèce", dial: "+30", digits: 10 },
  { code: "ro", name: "Roumanie", dial: "+40", digits: 9 },
  { code: "bg", name: "Bulgarie", dial: "+359", digits: 9 },
  { code: "hr", name: "Croatie", dial: "+385", digits: 9 },
  { code: "rs", name: "Serbie", dial: "+381", digits: 9 },
  { code: "hu", name: "Hongrie", dial: "+36", digits: 9 },
  { code: "cz", name: "Tchéquie", dial: "+420", digits: 9 },
  { code: "sk", name: "Slovaquie", dial: "+421", digits: 9 },
  { code: "si", name: "Slovénie", dial: "+386", digits: 8 },
  { code: "lt", name: "Lituanie", dial: "+370", digits: 8 },
  { code: "lv", name: "Lettonie", dial: "+371", digits: 8 },
  { code: "ee", name: "Estonie", dial: "+372", digits: 8 },
  { code: "lu", name: "Luxembourg", dial: "+352", digits: 9 },
  { code: "cy", name: "Chypre", dial: "+357", digits: 8 },
  { code: "mt", name: "Malte", dial: "+356", digits: 8 },
  { code: "is", name: "Islande", dial: "+354", digits: 7 },
  { code: "al", name: "Albanie", dial: "+355", digits: 9 },
  { code: "mk", name: "Macédoine du Nord", dial: "+389", digits: 8 },
  { code: "me", name: "Monténégro", dial: "+382", digits: 8 },
  { code: "ba", name: "Bosnie-Herzégovine", dial: "+387", digits: 8 },
  { code: "md", name: "Moldavie", dial: "+373", digits: 8 },
  { code: "ua", name: "Ukraine", dial: "+380", digits: 9 },
  { code: "by", name: "Biélorussie", dial: "+375", digits: 9 },
  { code: "ru", name: "Russie", dial: "+7", digits: 10 },
  { code: "ge", name: "Géorgie", dial: "+995", digits: 9 },
  { code: "am", name: "Arménie", dial: "+374", digits: 8 },
  { code: "az", name: "Azerbaïdjan", dial: "+994", digits: 9 },
  { code: "tr", name: "Turquie", dial: "+90", digits: 10 },
  { code: "mc", name: "Monaco", dial: "+377", digits: 8 },
  { code: "ad", name: "Andorre", dial: "+376", digits: 6 },
  { code: "li", name: "Liechtenstein", dial: "+423", digits: 7 },
  { code: "sm", name: "Saint-Marin", dial: "+378", digits: 8 },

  // Amérique du Nord
  { code: "us", name: "États-Unis", dial: "+1", digits: 10 },
  { code: "ca", name: "Canada", dial: "+1", digits: 10 },
  { code: "mx", name: "Mexique", dial: "+52", digits: 10 },

  // Amérique Centrale et Caraïbes
  { code: "gt", name: "Guatemala", dial: "+502", digits: 8 },
  { code: "hn", name: "Honduras", dial: "+504", digits: 8 },
  { code: "sv", name: "Salvador", dial: "+503", digits: 8 },
  { code: "ni", name: "Nicaragua", dial: "+505", digits: 8 },
  { code: "cr", name: "Costa Rica", dial: "+506", digits: 8 },
  { code: "pa", name: "Panama", dial: "+507", digits: 8 },
  { code: "cu", name: "Cuba", dial: "+53", digits: 8 },
  { code: "ht", name: "Haïti", dial: "+509", digits: 8 },
  { code: "do", name: "République dominicaine", dial: "+1809", digits: 7 },
  { code: "jm", name: "Jamaïque", dial: "+1876", digits: 7 },
  { code: "tt", name: "Trinité-et-Tobago", dial: "+1868", digits: 7 },
  { code: "bb", name: "Barbade", dial: "+1246", digits: 7 },
  { code: "bs", name: "Bahamas", dial: "+1242", digits: 7 },
  { code: "bz", name: "Belize", dial: "+501", digits: 7 },

  // Amérique du Sud
  { code: "br", name: "Brésil", dial: "+55", digits: 11 },
  { code: "ar", name: "Argentine", dial: "+54", digits: 10 },
  { code: "co", name: "Colombie", dial: "+57", digits: 10 },
  { code: "cl", name: "Chili", dial: "+56", digits: 9 },
  { code: "pe", name: "Pérou", dial: "+51", digits: 9 },
  { code: "ve", name: "Venezuela", dial: "+58", digits: 10 },
  { code: "ec", name: "Équateur", dial: "+593", digits: 9 },
  { code: "bo", name: "Bolivie", dial: "+591", digits: 8 },
  { code: "py", name: "Paraguay", dial: "+595", digits: 9 },
  { code: "uy", name: "Uruguay", dial: "+598", digits: 8 },
  { code: "gy", name: "Guyana", dial: "+592", digits: 7 },
  { code: "sr", name: "Suriname", dial: "+597", digits: 7 },

  // Moyen-Orient
  { code: "sa", name: "Arabie saoudite", dial: "+966", digits: 9 },
  { code: "ae", name: "Émirats arabes unis", dial: "+971", digits: 9 },
  { code: "qa", name: "Qatar", dial: "+974", digits: 8 },
  { code: "kw", name: "Koweït", dial: "+965", digits: 8 },
  { code: "bh", name: "Bahreïn", dial: "+973", digits: 8 },
  { code: "om", name: "Oman", dial: "+968", digits: 8 },
  { code: "ye", name: "Yémen", dial: "+967", digits: 9 },
  { code: "iq", name: "Irak", dial: "+964", digits: 10 },
  { code: "ir", name: "Iran", dial: "+98", digits: 10 },
  { code: "jo", name: "Jordanie", dial: "+962", digits: 9 },
  { code: "lb", name: "Liban", dial: "+961", digits: 8 },
  { code: "sy", name: "Syrie", dial: "+963", digits: 9 },
  { code: "il", name: "Israël", dial: "+972", digits: 9 },
  { code: "ps", name: "Palestine", dial: "+970", digits: 9 },

  // Asie
  { code: "cn", name: "Chine", dial: "+86", digits: 11 },
  { code: "jp", name: "Japon", dial: "+81", digits: 10 },
  { code: "kr", name: "Corée du Sud", dial: "+82", digits: 10 },
  { code: "in", name: "Inde", dial: "+91", digits: 10 },
  { code: "pk", name: "Pakistan", dial: "+92", digits: 10 },
  { code: "bd", name: "Bangladesh", dial: "+880", digits: 10 },
  { code: "id", name: "Indonésie", dial: "+62", digits: 10 },
  { code: "my", name: "Malaisie", dial: "+60", digits: 9 },
  { code: "th", name: "Thaïlande", dial: "+66", digits: 9 },
  { code: "vn", name: "Viêt Nam", dial: "+84", digits: 9 },
  { code: "ph", name: "Philippines", dial: "+63", digits: 10 },
  { code: "sg", name: "Singapour", dial: "+65", digits: 8 },
  { code: "mm", name: "Myanmar", dial: "+95", digits: 9 },
  { code: "kh", name: "Cambodge", dial: "+855", digits: 9 },
  { code: "la", name: "Laos", dial: "+856", digits: 9 },
  { code: "np", name: "Népal", dial: "+977", digits: 10 },
  { code: "lk", name: "Sri Lanka", dial: "+94", digits: 9 },
  { code: "af", name: "Afghanistan", dial: "+93", digits: 9 },
  { code: "uz", name: "Ouzbékistan", dial: "+998", digits: 9 },
  { code: "kz", name: "Kazakhstan", dial: "+7", digits: 10 },
  { code: "tm", name: "Turkménistan", dial: "+993", digits: 8 },
  { code: "kg", name: "Kirghizistan", dial: "+996", digits: 9 },
  { code: "tj", name: "Tadjikistan", dial: "+992", digits: 9 },
  { code: "mn", name: "Mongolie", dial: "+976", digits: 8 },
  { code: "tw", name: "Taïwan", dial: "+886", digits: 9 },
  { code: "hk", name: "Hong Kong", dial: "+852", digits: 8 },
  { code: "mo", name: "Macao", dial: "+853", digits: 8 },
  { code: "bn", name: "Brunei", dial: "+673", digits: 7 },
  { code: "bt", name: "Bhoutan", dial: "+975", digits: 8 },
  { code: "mv", name: "Maldives", dial: "+960", digits: 7 },
  { code: "tl", name: "Timor oriental", dial: "+670", digits: 8 },

  // Océanie
  { code: "au", name: "Australie", dial: "+61", digits: 9 },
  { code: "nz", name: "Nouvelle-Zélande", dial: "+64", digits: 9 },
  { code: "fj", name: "Fidji", dial: "+679", digits: 7 },
  { code: "pg", name: "Papouasie-Nouvelle-Guinée", dial: "+675", digits: 8 },
  { code: "ws", name: "Samoa", dial: "+685", digits: 7 },
  { code: "to", name: "Tonga", dial: "+676", digits: 7 },
  { code: "vu", name: "Vanuatu", dial: "+678", digits: 7 },

  // Territoires français
  { code: "gf", name: "Guyane française", dial: "+594", digits: 9 },
  { code: "gp", name: "Guadeloupe", dial: "+590", digits: 9 },
  { code: "mq", name: "Martinique", dial: "+596", digits: 9 },
  { code: "re", name: "La Réunion", dial: "+262", digits: 9 },
  { code: "nc", name: "Nouvelle-Calédonie", dial: "+687", digits: 6 },
  { code: "pf", name: "Polynésie française", dial: "+689", digits: 6 },
  { code: "yt", name: "Mayotte", dial: "+262", digits: 9 },
];
