package com.moov.pim.notification.domain;

public enum NotificationType {
    ENRICHMENT_REQUIRED, VALIDATION_REQUIRED, STRATEGIC_VALIDATION,
    OFFER_REJECTED, OFFER_PUBLISHED, OFFER_EXPIRING, CAMPAIGN_READY,
    OFFER_CREATED, MEDIA_VALIDATED, MEDIA_REJECTED,
    CAMPAIGN_PUBLISHED, CAMPAIGN_CANCELLED,
    AI_TASK_COMPLETED, AI_TASK_FAILED,
    CATALOG_ITEM_CREATED, CATALOG_ITEM_ARCHIVED,
    USER_REGISTERED
}
